import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/Layout/header";
import 'swiper/css';
import 'swiper/css/navigation';
import 'swiper/css/pagination';
import RootProvider from "@/redux/RootProvider";

const inter = Inter({ subsets: ["latin"] });

  export const metadata = {
    title: "Clone FlipCart ",
    description: "Generated by create next app",
    icons:{
      icon:"/flipkart_icon-icons.com_62718.ico"
    }
  };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <RootProvider>

        
        <Header/>
        {children}
        </RootProvider>
        </body>
    </html>
  );
}
